In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Dense # type: ignore
from tensorflow.keras.models import  load_model
import pandas as pd
import pickle
import numpy as np

d:\ANN_project\venv\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

In [348]:
#load the ann trained model.standard scalar,enocders

model=load_model('model.h5')

with open('geo_encoder.pkl','rb') as file:
    label_geo=pickle.load(file)

with open('gen_encoder.pkl','rb') as file:
    label_gen=pickle.load(file)    


with open('scalar.pkl','rb') as file:
    scalar=pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [353]:
input_data={
    "CreditScore":600,
    "Geography":"France",
    "Gender":"Male",
    "Age":40,
    "Tenure":3,
    "Balance":60000,
    "NumOfProducts":2,
    "HasCrCard":1,
    "IsActiveMember":1,
    "EstimatedSalary":50000
}

In [354]:
df_geo=label_geo.transform([[input_data['Geography']]]).toarray()
l1=pd.DataFrame(df_geo,columns=label_geo.get_feature_names_out(['Geography']))

d:\ANN_project\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [355]:
l1.first

<bound method NDFrame.first of    Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0>

In [316]:
[[input_data['Gender']]]

[['Male']]

In [356]:
df_gen=label_gen.transform([[input_data['Gender']]])
l2=pd.DataFrame(df_gen,columns=["Gender"])

d:\ANN_project\venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [273]:
input_data['Gender']=int(l2['Gender'])

C:\Users\HP\AppData\Local\Temp\ipykernel_12108\1682462070.py:1: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  input_data['Gender']=int(l2['Gender'])

In [287]:
input_data['Geography']=l1.iloc[0].values.tolist()

In [306]:
input_data['Geography']="France"

In [357]:
input_data

{'CreditScore': 600,
 'Geography': 'France',
 'Gender': 'Male',
 'Age': 40,
 'Tenure': 3,
 'Balance': 60000,
 'NumOfProducts': 2,
 'HasCrCard': 1,
 'IsActiveMember': 1,
 'EstimatedSalary': 50000}

In [358]:
input_df=pd.DataFrame([input_data])

In [359]:
input_df=pd.concat([input_df,l1],axis=1)
input_df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,France,Male,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [360]:
input_df['Gender']=label_gen.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,France,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [361]:
input_df.drop("Geography",axis=1,inplace=True)

In [362]:
input_scaled=scalar.transform(input_df)
input_scaled

array([[-0.51117389,  0.92249385,  0.10355574, -0.6968392 , -0.26495898,
         0.80710531,  0.64842466,  0.96995125, -0.86720007,  0.9922798 ,
        -0.57792762, -0.57080675]])

In [ ]:
prediction=model.predict(input_scaled)

In [363]:
!pip   install streamlit

Collecting streamlit
  Downloading streamlit-1.52.2-py3-none-any.whl.metadata (9.8 kB)
Collecting altair!=5.4.0,!=5.4.1,<7,>=4.0 (from streamlit)
  Downloading altair-6.0.0-py3-none-any.whl.metadata (11 kB)
Collecting blinker<2,>=1.5.0 (from streamlit)
  Using cached blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting cachetools<7,>=4.0 (from streamlit)
  Downloading cachetools-6.2.4-py3-none-any.whl.metadata (5.6 kB)
Collecting click<9,>=7.0 (from streamlit)
  Downloading click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: numpy<3,>=1.23 in d:\ann_project\venv\lib\site-packages (from streamlit) (2.4.1)
Requirement already satisfied: packaging>=20 in d:\ann_project\venv\lib\site-packages (from streamlit) (25.0)
Requirement already satisfied: pandas<3,>=1.4.0 in d:\ann_project\venv\lib\site-packages (from streamlit) (2.3.3)
Requirement already satisfied: pillow<13,>=7.1.0 in d:\ann_project\venv\lib\site-packages (from streamlit) (12.1.0)
Requirement already satisfied: protobuf<7,>=3.20 in d:\ann_project\venv\lib\site-packages (from streamlit) (6.33.3)
Collecting pyarrow>=7.0 (from streamlit)
  Downloading pyarrow-22.0.0-cp311-cp311-win_amd64.whl.metadata (3.3 kB)
Requirement already satisfied: requests<3,>=2.27 in d:\ann_project\venv\lib\site-packages (from streamlit) (2.32.5)
Collecting tenacity<10,>=8.1.0 (from streamlit)
  Using cached tenacity-9.1.2-py3-none-any.whl.metadata (1.2 kB)
Collecting toml<2,>=0.10.1 (from streamlit)
  Using cached toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in d:\ann_project\venv\lib\site-packages (from streamlit) (4.15.0)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Using cached watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Downloading gitpython-3.1.46-py3-none-any.whl.metadata (13 kB)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Using cached pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in d:\ann_project\venv\lib\site-packages (from streamlit) (6.5.4)
Collecting jinja2 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting jsonschema>=3.0 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting narwhals>=1.27.1 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading narwhals-2.15.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: colorama in d:\ann_project\venv\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Using cached gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Using cached smmap-5.0.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\ann_project\venv\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\ann_project\venv\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\ann_project\venv\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\ann_project\venv\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in d:\ann_project\venv\lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\ann_project\venv\lib\site-packages (from requests<3,>=2.27->streamlit) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in d:\ann_project\venv\lib\site-packages (from requests<3,>=2.27->streamlit) (2026.1.4)
Requirement already satisfied: MarkupSafe>=2.0 in d:\ann_project\venv\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Collecting attrs>=22.2.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading rpds_py-0.30.0-cp311-cp311-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: six>=1.5 in d:\ann_project\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.52.2-py3-none-any.whl (9.0 MB)
   ---------------------------------------- 0.0/9.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.0 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.0 MB 1.8 MB/s eta 0:00:05
   ---- ----------------------------------- 1.0/9.0 MB 1.8 MB/s eta 0:00:05
   ------ --------------------------------- 1.6/9.0 MB 2.0 MB/s eta 0:00:04
   -------- ------------------------------- 1.8/9.0 MB 1.8 MB/s eta 0:00:04
   -------- ------------------------------- 1.8/9.0 MB 1.8 MB/s eta 0:00:04
   --------- ------------------------------ 2.1/9.0 MB 1.5 MB/s eta 0:00:05
   ---------- ----------------------------- 2.4/9.0 MB 1.4 MB/s eta 0:00:05
   ---------- ----------------------------- 2.4/9.0 MB 1.4 MB/s eta 0:00:05
   ----------- ---------------------------- 2.6/9.0 MB 1.2 MB/s eta 0:00:06
   ----------- ---------------------------- 2.6/9.0 MB 1.2 MB/s eta 0:00:06
   ------------ --------------------------- 2.9/9.0 MB 1.2 MB/s eta 0:00:06
   ------------ --------------------------- 2.9/9.0 MB 1.2 MB/s eta 0:00:06
   ------------- -------------------------- 3.1/9.0 MB 1.0 MB/s eta 0:00:06
   --------------- ------------------------ 3.4/9.0 MB 1.0 MB/s eta 0:00:06
   --------------- ------------------------ 3.4/9.0 MB 1.0 MB/s eta 0:00:06
   ---------------- ----------------------- 3.7/9.0 MB 986.9 kB/s eta 0:00:06
   ----------------- ---------------------- 3.9/9.0 MB 986.8 kB/s eta 0:00:06
   ----------------- ---------------------- 3.9/9.0 MB 986.8 kB/s eta 0:00:06
   ------------------ --------------------- 4.2/9.0 MB 942.5 kB/s eta 0:00:06
   ------------------ --------------------- 4.2/9.0 MB 942.5 kB/s eta 0:00:06
   ------------------- -------------------- 4.5/9.0 MB 916.2 kB/s eta 0:00:05
   ------------------- -------------------- 4.5/9.0 MB 916.2 kB/s eta 0:00:05
   -------------------- ------------------- 4.7/9.0 MB 894.1 kB/s eta 0:00:05
   -------------------- ------------------- 4.7/9.0 MB 894.1 kB/s eta 0:00:05
   -------------------- ------------------- 4.7/9.0 MB 894.1 kB/s eta 0:00:05
   ---------------------- ----------------- 5.0/9.0 MB 834.3 kB/s eta 0:00:05
   ---------------------- ----------------- 5.0/9.0 MB 834.3 kB/s eta 0:00:05
   ----------------------- ---------------- 5.2/9.0 MB 827.9 kB/s eta 0:00:05
   ----------------------- ---------------- 5.2/9.0 MB 827.9 kB/s eta 0:00:05
   ------------------------ --------------- 5.5/9.0 MB 802.8 kB/s eta 0:00:05
   ------------------------ --------------- 5.5/9.0 MB 802.8 kB/s eta 0:00:05
   ------------------------ --------------- 5.5/9.0 MB 802.8 kB/s eta 0:00:05
   ------------------------- -------------- 5.8/9.0 MB 770.9 kB/s eta 0:00:05
   -------------------------- ------------- 6.0/9.0 MB 790.3 kB/s eta 0:00:04
   --------------------------- ------------ 6.3/9.0 MB 810.6 kB/s eta 0:00:04
   --------------------------- ------------ 6.3/9.0 MB 810.6 kB/s eta 0:00:04
   ----------------------------- ---------- 6.6/9.0 MB 789.5 kB/s eta 0:00:04
   ----------------------------- ---------- 6.6/9.0 MB 789.5 kB/s eta 0:00:04
   ----------------------------- ---------- 6.6/9.0 MB 789.5 kB/s eta 0:00:04
   ----------------------------- ---------- 6.6/9.0 MB 789.5 kB/s eta 0:00:04
   ------------------------------ --------- 6.8/9.0 MB 737.1 kB/s eta 0:00:03
   ------------------------------ --------- 6.8/9.0 MB 737.1 kB/s eta 0:00:03
   ------------------------------- -------- 7.1/9.0 MB 735.6 kB/s eta 0:00:03
   ------------------------------- -------- 7.1/9.0 MB 735.6 kB/s eta 0:00:03
   ------------------------------- -------- 7.1/9.0 MB 735.6 kB/s eta 0:00:03
   -------------------------------- ------- 7.3/9.0 MB 716.7 kB/s eta 0:00:03
   -------------------------------- ------- 7.3/9.0 MB 716.7 kB/s eta 0:00:03
   -------------------------------- ------- 7.3/9.0 MB 716.7 kB/s eta 0:00:03
   -------------------------------- ------- 7.3/9.0 MB 716.7 kB/s eta 0:00:03
   --------------------------------- ------ 7.6/9.0 MB 679.8 kB/s eta 0:00:03
   ---------------------------------- ----- 7.9/9.0 MB 691.1 kB/s eta 0:00:02
   ------------------------------------ --- 8.1/9.0 MB 705.9 kB/s eta 0:00:02
   ------------------------------------- -- 8.4/9.0 MB 715.4 kB/s eta 0:00:01
   ------------------------------------- -- 8.4/9.0 MB 715.4 kB/s eta 0:00:01
   ------------------------------------- -- 8.4/9.0 MB 715.4 kB/s eta 0:00:01
   -------------------------------------- - 8.7/9.0 MB 698.1 kB/s eta 0:00:01
   -------------------------------------- - 8.7/9.0 MB 698.1 kB/s eta 0:00:01
   -------------------------------------- - 8.7/9.0 MB 698.1 kB/s eta 0:00:01
   -------------------------------------- - 8.7/9.0 MB 698.1 kB/s eta 0:00:01
   -------------------------------------- - 8.7/9.0 MB 698.1 kB/s eta 0:00:01
   ---------------------------------------- 9.0/9.0 MB 664.5 kB/s  0:00:13
Downloading altair-6.0.0-py3-none-any.whl (795 kB)
   ---------------------------------------- 0.0/795.4 kB ? eta -:--:--
   ---------------------------------------- 0.0/795.4 kB ? eta -:--:--
   ---------------------------------------- 0.0/795.4 kB ? eta -:--:--
   ------------- -------------------------- 262.1/795.4 kB ? eta -:--:--
   ------------- -------------------------- 262.1/795.4 kB ? eta -:--:--
   ------------------------- ------------ 524.3/795.4 kB 524.3 kB/s eta 0:00:01
   ------------------------- ------------ 524.3/795.4 kB 524.3 kB/s eta 0:00:01
   ---------------------------------------- 795.4/795.4 kB 550.3 kB/s  0:00:01
Using cached blinker-1.9.0-py3-none-any.whl (8.5 kB)
Downloading cachetools-6.2.4-py3-none-any.whl (11 kB)
Downloading click-8.3.1-py3-none-any.whl (108 kB)
Downloading gitpython-3.1.46-py3-none-any.whl (208 kB)
Using cached gitdb-4.0.12-py3-none-any.whl (62 kB)
Using cached pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
Using cached smmap-5.0.2-py3-none-any.whl (24 kB)
Using cached tenacity-9.1.2-py3-none-any.whl (28 kB)
Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Using cached watchdog-6.0.0-py3-none-win_amd64.whl (79 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Downloading jsonschema-4.26.0-py3-none-any.whl (90 kB)
Downloading attrs-25.4.0-py3-none-any.whl (67 kB)
Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Downloading narwhals-2.15.0-py3-none-any.whl (432 kB)
Downloading pyarrow-22.0.0-cp311-cp311-win_amd64.whl (28.1 MB)
   ---------------------------------------- 0.0/28.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/28.1 MB ? eta -:--:--
    --------------------------------------- 0.5/28.1 MB 2.4 MB/s eta 0:00:12
   - -------------------------------------- 0.8/28.1 MB 2.4 MB/s eta 0:00:12
   - -------------------------------------- 1.0/28.1 MB 1.6 MB/s eta 0:00:18
   - -------------------------------------- 1.3/28.1 MB 1.6 MB/s eta 0:00:18
   -- ------------------------------------- 1.6/28.1 MB 1.5 MB/s eta 0:00:18
   -- ------------------------------------- 1.6/28.1 MB 1.5 MB/s eta 0:00:18
   -- ------------------------------------- 1.8/28.1 MB 1.2 MB/s eta 0:00:22
   -- ------------------------------------- 2.1/28.1 MB 1.1 MB/s eta 0:00:24
   -- ------------------------------------- 2.1/28.1 MB 1.1 MB/s eta 0:00:24
   --- ------------------------------------ 2.4/28.1 MB 1.1 MB/s eta 0:00:25
   --- ------------------------------------ 2.4/28.1 MB 1.1 MB/s eta 0:00:25
   --- ------------------------------------ 2.4/28.1 MB 1.1 MB/s eta 0:00:25
   --- ------------------------------------ 2.4/28.1 MB 1.1 MB/s eta 0:00:25
   --- ------------------------------------ 2.6/28.1 MB 857.9 kB/s eta 0:00:30
   --- ------------------------------------ 2.6/28.1 MB 857.9 kB/s eta 0:00:30
   ---- ----------------------------------- 2.9/28.1 MB 787.7 kB/s eta 0:00:33
   ---- ----------------------------------- 2.9/28.1 MB 787.7 kB/s eta 0:00:33
   ---- ----------------------------------- 2.9/28.1 MB 787.7 kB/s eta 0:00:33
   ---- ----------------------------------- 2.9/28.1 MB 787.7 kB/s eta 0:00:33
   ---- ----------------------------------- 2.9/28.1 MB 787.7 kB/s eta 0:00:33
   ---- ----------------------------------- 2.9/28.1 MB 787.7 kB/s eta 0:00:33
   ---- ----------------------------------- 2.9/28.1 MB 787.7 kB/s eta 0:00:33
   ---- ----------------------------------- 3.1/28.1 MB 603.1 kB/s eta 0:00:42
   ---- ----------------------------------- 3.1/28.1 MB 603.1 kB/s eta 0:00:42
   ---- ----------------------------------- 3.4/28.1 MB 606.3 kB/s eta 0:00:41
   ---- ----------------------------------- 3.4/28.1 MB 606.3 kB/s eta 0:00:41
   ----- ---------------------------------- 3.7/28.1 MB 595.9 kB/s eta 0:00:42
   ----- ---------------------------------- 3.7/28.1 MB 595.9 kB/s eta 0:00:42
   ----- ---------------------------------- 3.9/28.1 MB 597.6 kB/s eta 0:00:41
   ----- ---------------------------------- 3.9/28.1 MB 597.6 kB/s eta 0:00:41
   ----- ---------------------------------- 4.2/28.1 MB 597.8 kB/s eta 0:00:41
   ----- ---------------------------------- 4.2/28.1 MB 597.8 kB/s eta 0:00:41
   ------ --------------------------------- 4.5/28.1 MB 597.8 kB/s eta 0:00:40
   ------ --------------------------------- 4.5/28.1 MB 597.8 kB/s eta 0:00:40
   ------ --------------------------------- 4.5/28.1 MB 597.8 kB/s eta 0:00:40
   ------ --------------------------------- 4.7/28.1 MB 594.2 kB/s eta 0:00:40
   ------ --------------------------------- 4.7/28.1 MB 594.2 kB/s eta 0:00:40
   ------ --------------------------------- 4.7/28.1 MB 594.2 kB/s eta 0:00:40
   ------ --------------------------------- 4.7/28.1 MB 594.2 kB/s eta 0:00:40
   ------ --------------------------------- 4.7/28.1 MB 594.2 kB/s eta 0:00:40
   ------- -------------------------------- 5.0/28.1 MB 548.1 kB/s eta 0:00:43
   ------- -------------------------------- 5.0/28.1 MB 548.1 kB/s eta 0:00:43
   ------- -------------------------------- 5.2/28.1 MB 545.8 kB/s eta 0:00:42
   ------- -------------------------------- 5.2/28.1 MB 545.8 kB/s eta 0:00:42
   ------- -------------------------------- 5.5/28.1 MB 553.7 kB/s eta 0:00:41
   -------- ------------------------------- 6.0/28.1 MB 594.4 kB/s eta 0:00:38
   -------- ------------------------------- 6.0/28.1 MB 594.4 kB/s eta 0:00:38
   -------- ------------------------------- 6.3/28.1 MB 601.1 kB/s eta 0:00:37
   -------- ------------------------------- 6.3/28.1 MB 601.1 kB/s eta 0:00:37
   --------- ------------------------------ 6.6/28.1 MB 596.5 kB/s eta 0:00:37
   --------- ------------------------------ 6.6/28.1 MB 596.5 kB/s eta 0:00:37
   --------- ------------------------------ 6.6/28.1 MB 596.5 kB/s eta 0:00:37
   --------- ------------------------------ 6.8/28.1 MB 590.7 kB/s eta 0:00:37
   --------- ------------------------------ 6.8/28.1 MB 590.7 kB/s eta 0:00:37
   ---------- ----------------------------- 7.1/28.1 MB 583.1 kB/s eta 0:00:37
   ---------- ----------------------------- 7.1/28.1 MB 583.1 kB/s eta 0:00:37
   ---------- ----------------------------- 7.1/28.1 MB 583.1 kB/s eta 0:00:37
   ---------- ----------------------------- 7.6/28.1 MB 598.4 kB/s eta 0:00:35
   ----------- ---------------------------- 7.9/28.1 MB 605.1 kB/s eta 0:00:34
   ----------- ---------------------------- 7.9/28.1 MB 605.1 kB/s eta 0:00:34
   ----------- ---------------------------- 7.9/28.1 MB 605.1 kB/s eta 0:00:34
   ----------- ---------------------------- 7.9/28.1 MB 605.1 kB/s eta 0:00:34
   ----------- ---------------------------- 8.1/28.1 MB 590.1 kB/s eta 0:00:34
   ----------- ---------------------------- 8.1/28.1 MB 590.1 kB/s eta 0:00:34
   ----------- ---------------------------- 8.1/28.1 MB 590.1 kB/s eta 0:00:34
   ----------- ---------------------------- 8.1/28.1 MB 590.1 kB/s eta 0:00:34
   ----------- ---------------------------- 8.4/28.1 MB 570.9 kB/s eta 0:00:35
   ----------- ---------------------------- 8.4/28.1 MB 570.9 kB/s eta 0:00:35
   ------------ --------------------------- 8.7/28.1 MB 576.7 kB/s eta 0:00:34
   ------------- -------------------------- 9.2/28.1 MB 600.4 kB/s eta 0:00:32
   ------------- -------------------------- 9.7/28.1 MB 627.8 kB/s eta 0:00:30
   -------------- ------------------------- 10.0/28.1 MB 640.6 kB/s eta 0:00:29
   -------------- ------------------------- 10.2/28.1 MB 640.1 kB/s eta 0:00:28
   -------------- ------------------------- 10.2/28.1 MB 640.1 kB/s eta 0:00:28
   -------------- ------------------------- 10.5/28.1 MB 644.0 kB/s eta 0:00:28
   -------------- ------------------------- 10.5/28.1 MB 644.0 kB/s eta 0:00:28
   --------------- ------------------------ 10.7/28.1 MB 642.8 kB/s eta 0:00:28
   --------------- ------------------------ 11.0/28.1 MB 648.9 kB/s eta 0:00:27
   ---------------- ----------------------- 11.5/28.1 MB 671.1 kB/s eta 0:00:25
   ---------------- ----------------------- 11.8/28.1 MB 678.5 kB/s eta 0:00:25
   ----------------- ---------------------- 12.3/28.1 MB 699.7 kB/s eta 0:00:23
   ----------------- ---------------------- 12.6/28.1 MB 709.8 kB/s eta 0:00:22
   ------------------ --------------------- 12.8/28.1 MB 717.8 kB/s eta 0:00:22
   ------------------ --------------------- 12.8/28.1 MB 717.8 kB/s eta 0:00:22
   ------------------ --------------------- 12.8/28.1 MB 717.8 kB/s eta 0:00:22
   ------------------ --------------------- 13.1/28.1 MB 707.5 kB/s eta 0:00:22
   ------------------- -------------------- 13.4/28.1 MB 709.7 kB/s eta 0:00:21
   ------------------- -------------------- 13.4/28.1 MB 709.7 kB/s eta 0:00:21
   ------------------- -------------------- 13.6/28.1 MB 709.5 kB/s eta 0:00:21
   ------------------- -------------------- 13.6/28.1 MB 709.5 kB/s eta 0:00:21
   ------------------- -------------------- 13.9/28.1 MB 704.7 kB/s eta 0:00:21
   ------------------- -------------------- 13.9/28.1 MB 704.7 kB/s eta 0:00:21
   -------------------- ------------------- 14.2/28.1 MB 700.1 kB/s eta 0:00:20
   -------------------- ------------------- 14.2/28.1 MB 700.1 kB/s eta 0:00:20
   -------------------- ------------------- 14.4/28.1 MB 701.8 kB/s eta 0:00:20
   -------------------- ------------------- 14.4/28.1 MB 701.8 kB/s eta 0:00:20
   -------------------- ------------------- 14.7/28.1 MB 695.9 kB/s eta 0:00:20
   -------------------- ------------------- 14.7/28.1 MB 695.9 kB/s eta 0:00:20
   -------------------- ------------------- 14.7/28.1 MB 695.9 kB/s eta 0:00:20
   -------------------- ------------------- 14.7/28.1 MB 695.9 kB/s eta 0:00:20
   --------------------- ------------------ 14.9/28.1 MB 684.8 kB/s eta 0:00:20
   --------------------- ------------------ 14.9/28.1 MB 684.8 kB/s eta 0:00:20
   --------------------- ------------------ 15.2/28.1 MB 681.6 kB/s eta 0:00:19
   --------------------- ------------------ 15.2/28.1 MB 681.6 kB/s eta 0:00:19
   ---------------------- ----------------- 15.5/28.1 MB 680.0 kB/s eta 0:00:19
   ---------------------- ----------------- 15.7/28.1 MB 686.0 kB/s eta 0:00:19
   ---------------------- ----------------- 16.0/28.1 MB 692.8 kB/s eta 0:00:18